services:
  mysql:
    image: mysql:8.4
    container_name: vitalmind-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vitalmind
      MYSQL_USER: vitalmind
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

volumes:
  mysql_data:
